services:
  - type: worker
    name: tele-bot-worker
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ACADEMI_USERNAME
        sync: false
      - key: ACADEMI_PASSWORD
        sync: false
      - key: RENDER_URL
        value: ""   # leave empty for polling
