services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ACADEMI_USERNAME
        sync: false
      - key: ACADEMI_PASSWORD
        sync: false
      - key: RENDER_URL
        sync: false
      - key: PORT
        value: 10000